version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: bookstore_user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: bookstore